spring:
  datasource:
    url: jdbc:mysql://localhost:3306/burger_api?createDatabaseIfNotExist=true
    username: root
    password: 20051216

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

